---
title: "Figure"
author: "Brady Nahkala"
date: "9/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Library

```{r, warning=F, message=F}
library(tidyr)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(RColorBrewer)
```

# Input Data

```{r}
nutrients <- read.csv(file = "./data/NutrientBoxplotsData.csv", header=T, sep=",")
# values <- nutrients$Value

nutrients <- nutrients[ , c(1:3)] %>%
  filter(Value != "") %>%
  filter(Value < 1500)
# nutrients$Value <- as.numeric(levels(nutrients$Value))[nutrients$Value]


nutrients$Season <- factor(nutrients$Season, levels=c("R-E", "R-L", "S-E", "S-L", "C-E", "C-L"))


```


# Figure

```{r, fig.width=5.3, fig.height=5.3}
# ggplot(nutrients[nutrients$Nutrient == "Ammonia", ], aes(Season, Value))+
  # geom_boxplot()

Fig5 <- ggplot(nutrients)+
  geom_boxplot(aes(x=Season, y=Value))+
  facet_wrap(~Nutrient, nrow=3, ncol=2, scales = "free")+
  theme_bw(base_size = 9)

Fig5
```

```{r}
png(filename = "05_NutrientBoxplots.png", width=135, height=135, units="mm", res=300)
Fig5
dev.off()
```

